module.exports = {
    "env": {
        "node": true,
        "es6": true
    },
    "rules": {
        "eslint-comments/require-description": [
            "error",
            {"ignore": ["eslint-enable"]}
        ],
        "array-callback-return": ["error", {"checkForEach": true}],
        "constructor-super": "error",
        "for-direction": "error",
        "getter-return": "error",
        "no-async-promise-executor": "error",
        "no-await-in-loop": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-dupe-args": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-duplicate-imports": "error",
        "no-empty-character-class": "error",
        "no-empty-pattern": "error",
        "no-ex-assign": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-import-assign": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "error",
        "no-obj-calls": "error",
        "no-promise-executor-return": "error",
        "no-prototype-builtins": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-setter-return": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "error",
        "no-unexpected-multiline": "error",
        "no-unmodified-loop-condition": "error",
        "no-unreachable": "error",
        "no-unreachable-loop": "error",
        "no-unused-private-class-members": "error",
        "no-useless-backreference": "error",
        "require-atomic-updates": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
        "no-unsafe-optional-chaining": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "block-scoped-var": "error",
        "class-methods-use-this": "error",
        "complexity": ["error", 50],
        "default-case": "error",
        "default-case-last": "error",
        "consistent-return": "error",
        "eqeqeq": "error",
        "func-style": ["error", "declaration", {"allowArrowFunctions": true}],
        "no-alert": "error",
        "no-case-declarations": "error",
        "no-confusing-arrow": "error",
        "no-delete-var": "error",
        "no-else-return": "error",
        "no-empty": "error",
        "no-eq-null": "error",
        "no-extra-semi": "error",
        "no-global-assign": "error",
        "no-implicit-coercion": "error",
        "no-label-var": "error",
        "no-lonely-if": "error",
        "no-nested-ternary": "error",
        "no-redeclare": "error",
        "no-useless-escape": "error",
        "no-useless-return": "error",
        "no-var": "error",
        "prefer-const": "error",
        "require-await": "error",
        "require-yield": "error",
        "yoda": "error"
    }
}